inherit_mode:
  merge:
    - Include

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  Enabled: false

Metrics/ModuleLength:
  Max: 250

Naming/FileName:
  Enabled: false

Style/BlockComments:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
